modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="tsiot1145"
version="1.0.0"
displayName="The Strange Idea of Taskschd1145"
displayURL="https://taskschd.us.kg"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Taskschd1145"
description="A Minecraft1.21.1 Mod that incorporates my bizarre ideas"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tsiot1145]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tsiot1145]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration